baseURL = "https://eloquent-gates-16ab6c.netlify.com/"
languageCode = "en-us"
title = "The Eggman site"
theme = "crakjie"

[params]
  description = "Dr Eggman and I have lots in common..."
  mainIcon = "img/Dr_Eggman.png"

[[params.social]]
    title = "GitHub"
    url = "https://github.com/AvutE"
[[params.social]]
    title = "About me"
    url = "/posts/this-is-me"
[[params.social]]
    title = "linkedin"
    url = "https://www.linkedin.com/in/tuva-e-8b5bb5133/"