baseURL = "https://eloquent-gates-16ab6c.netlify.com/"
languageCode = "en-us"
title = "About me"
theme = "crakjie"

[params]
  description = "I <3 making web sites"
  mainIcon = "http://enacademic.com/pictures/enwiki/69/Eggman_pose_29.jpg"

[[params.social]]
    title = "github"
    url = "https://github.com/AvutE"
[[params.social]]
    title = "linkedin"
    url = "https://www.linkedin.com/in/tuva-e-8b5bb5133/"