baseURL = "https://eloquent-gates-16ab6c.netlify.com/"
languageCode = "en-us"
title = "About me"
theme = "crakjie"

[params]
  description = "I <3 making web site"
  mainIcon = "/img/hugo.png"

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/SBootstrap"
[[params.social]]
    title = "github"
    url = "https://github.com/IronSummitMedia/startbootstrap"
[[params.social]]
    title = "linkedin"
    url = ""